name: Build Debian kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TMPDIR: /tmp

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y fakeroot git kernel-wedge quilt ccache flex bison libssl-dev dh-exec rsync libelf-dev bc crossbuild-essential-armhf=12.8ubuntu1 python3-jinja2 libncurses-dev

    - name: Get kernel
      run: |
        wget https://deb.debian.org/debian/pool/main/l/linux/linux_6.1.99.orig.tar.xz

    - name: Clone git repo
      run: |
        git clone -n https://salsa.debian.org/kernel-team/linux.git debian-kernel
        cd debian-kernel
        git checkout bookworm
        cd ..

    - name: Run Build
      run: |
        chmod 755 ./crossbuild.sh
        ./crossbuild.sh
