name: Compile Linux Kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: "Kernel version"
        required: true
        default: '6.1.99-1'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
  
      - name: Build Docker image
        run: |
          docker build -t bookworm .

      - name: Compile kernel
        run: |
          docker run -it --name kernel-ix4-300d -d bookworm:latest
          sleep 5
          docker exec kernel-ix4-300d /root/crossbuild.sh

      - name: Retrieve artifact from Docker image
        run: |
          rm -rf ${{ github.workspace }}/kernel-packages
          mkdir ${{ github.workspace }}/kernel-packages
          docker exec kernel-ix4-300d ls -la /root
          for file in $(docker exec kernel-ix4-300d sh -c 'ls /root/linux-*.deb'); do
            docker cp kernel-ix4-300d:$file ${{ github.workspace }}/kernel-packages
          done

      - name: Commit and push kernel ${{ github.event.inputs.tag }} files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release kernel ${{ github.event.inputs.tag }}"
          git push origin HEAD:master
          git tag ${{ github.event.inputs.tag }}
          git push --tags

      - name: Create release ${{ github.event.inputs.tag }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: lenovo-ix4-300d-debian-bookworm-kernel
          path: ${{ github.workspace }}/kernel-packages/linux-*.deb
