name: Compile Linux Kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
  
      - name: Build Docker image
        run: |
          docker build -t bookworm .

      - name: Compile kernel
        run: |
          docker run -it --name kernel-ix4-300d -d bookworm:latest
          sleep 5
          docker exec kernel-ix4-300d /root/crossbuild

      - name: Retrieve artifact from Docker image
        run: |
          docker exec kernel-ix4-300d ls -la /root
          for file in $(docker exec kernel-ix4-300d ls /root/linux-*.deb); do
            docker cp kernel-ix4-300d:/root/$file ${{ github.workspace }}
          done

      - uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: ${{ github.workspace }}/linux-*.deb
