name: Compile Linux Kernel

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=104857600
      
      - name: Build Docker image
        run: |
          docker build -t bookworm .

      - name: Compile kernel
        run: |
          docker run -it --name kernel-ix4-300d -d bookworm:latest
          docker exec kernel-ix4-300d /root/crossbuild          

      - name: Retrieve artifact from Docker image
        run: |
          HOME_DIR=$(docker exec kernel-ix4-300d sh -c 'echo $HOME')
          docker cp kernel:$HOME_DIR/linux-*.deb ${{ github.workspace }}          

      - uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: ${{ github.workspace }}/linux-*.deb
